spring:
  cloud:
    config:
      username: "${SPRING-SECURITY-NAME}"
      password: "${SPRING-SECURITY-PASSWORD}"
  #      uri: "localhost"
  config:
    import: "configserver:"
  application:
    name: web-service
