server:
  port: 8091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    url: ${POSTGRE_AUTHDB}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true