apiVersion: apps/v1

kind: Deployment

metadata:
  name: deploymentelasticsearch

spec:
  selector:
    matchLabels:
      app: deploymentelasticsearch

  template:
    metadata:
      labels:
        app: deploymentelasticsearch
        loadbalancer: loadpods

    spec:
      containers:
        - name: elasticsearch

          image: elasticsearch:7.17.0

          resources:
            limits:
              memory: "1024Mi"

              cpu: "200m"

          ports:
            - containerPort: 9200

            - containerPort: 9300

      env:
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx2048m
