version: '3.8'
services:
  bilgeadammongodb:
    image: mongo
    restart: always
    ports:
      - '27100:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root



