kind: Service
apiVersion: v1
metadata:
  name:  clusteripzipkin
  labels:
    clusterips: toolsbos
spec:
  type: NodePort
  selector:
    app:  deploymentzipkin
    loadzipkin: deploymentzipkin
  ports:
  - name:  zipkintcp
    port: 9411
    targetPort:  9411
    nodePort: 32222