apiVersion: v1
kind: ConfigMap
metadata:
  name: bilgevonfigmap  
data:
  MONGO_URL: "localhost"
  MONGO_ADMIN: "root"
  MONGO_PASWORD: "root"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmappod  
spec:
  containers:
  - name: configmappod
    image: muhammedali55/XXXX
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name:  MONGO_URL_POD
        valueFrom:
          configMapKeyRef:
            name:  bilgevonfigmap
            key: MONGO_URL
      - name:  MONGO_ADMIN_POD
        valueFrom:
          configMapKeyRef:
            name:  bilgevonfigmap
            key: MONGO_ADMIN    
    ports:
      - containerPort: 80
