apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: muhammedali55/CCC
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: myapp
              operator: In
              values:
                - bilge
      - weight: 2
        preference:
          matchExpressions:
            - key: myapp
              operator: In
              values:
                - adam
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: muhammedali55/CCC    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: myapp # myapp key değeri değeri bilge olan bir nodes varsa oluştur
                operator: In #In, NotIn, Exists, DoesNotExist
                values:
                - bilge  

    