apiVersion: v1
kind: Pod
metadata:
  name: volumepath
  labels:
    name: volumepath
spec:
  containers:
  - name: volumacontainer
    image: muhammedali55/tinyimagevolume
    volumeMounts:
      - name:  directory-volume
        mountPath:  /logs
      - name: file-volume
        mountPath: /logs/alllogs.log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name:  directory-volume  # Zaten container üzerinde var olan bir dizini belirtir.
    hostPath:
      path: /logs
      type: Directory
  - name:  dircreative-volume # bir dizin oluştur ancak eğer bu dizin zaten container üzerinde var ise oluşturma
    hostPath:
      path: /temp
      type: DirectoryOrCreate
  - name: file-volume  # Eğer alllogs.log dosyası yok ise oluştur diyoruz.
    hostPath:
      path: /logs/alllogs.log
      type: FileOrCreate

      