apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresqldbclaim
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: postgre
