apiVersion: v1
kind: Service
metadata:
  name: servive-web-loadbalancer
spec:
  selector:
    team: frontanddeveloper #Pod lara bağlantı kuruyor.
  type: NodePort
  ports:
  - port: 9091 # Bu port, kernates içinde geçerli olan yani, herhangi bir 
               # pod un erişimi sırasında kulllanacağı port tur.
               # Dışarıdan gelen istekler bu porta gelmelidir.
    targetPort: 80 # Podlar da ulaşılması gereken port tur.
                   # Dışarıdan gelen port istekleri bu
                   # porta yönlendirilir
    nodePort: 30001 # Dışa açılan port u hedefler