apiVersion: v1
kind: Service
metadata:
  name: servive-rest-loadbalancer
spec:
  selector:
    team: backenddeveloper #Pod lara bağlantı kuruyor.
  type: ClusterIP
  ports:
  - port: 9090 # Dışa açılan port u hedefler
               # Dışarıdan gelen istekler bu porta gelmelidir.
    targetPort: 80 # Podlar da ulaşılması gereken port tur.
                   # Dışarıdan gelen port istekleri bu
                   # porta yönlendirilir
    