server:
  port: ${auth_service_port}

spring:
  rabbitmq:
    host: ${spring_rabbit_host}
    port: ${spring_rabbit_port}
    username: ${spring_rabbit_username}
    password: ${spring_rabbit_password}

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${auth_service_spring_postgres_username}
    password: ${auth_service_spring_postgres_password}
    url: ${auth_service_spring_postgres_url}
  zipkin:
    enabled: true
    base-url:  ${zipkin_base_url}
    service:
      name: auth-server


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


myapplication:
  userservice: ${auth_service_spring_postgres_myapplication_userservice}


logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: authservice.log