server:
  port: 8091

spring:
  rabbitmq:
    host: 34.116.240.199
    port: 5672
    username: BilgeAdamAdmin
    password: BilgeAdam!**

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: BilgeAdam!**
    url: jdbc:postgresql://34.118.86.223:5432/authdb
  zipkin:
    enabled: true
    base-url: http://34.116.241.185:9411/
    service:
      name: auth-server


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


myapplication:
  userservice: ${MY-IP}:8090


logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: authservice.log