server:
  port: 8090

spring:
  rabbitmq:
    host: 34.134.25.134
    port: 5672
    username: BilgeAdamAdmin
    password: BilgeAdam!**
  data:
    mongodb:
      database: socialmedia
      username: bilgeadamuser
      password: '!bilgeadam**'
      host: 35.188.98.234
      port: 27017

  zipkin:
    enabled: true
    base-url:  http://34.134.25.134:9411/
    service:
      name: user-server


logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: userservice.log