server:
  port: ${web_service_spring_port}

s3:
  accesskey: ${aws_access_key}
  secretkey: ${aws_secret_key}

spring:
  security:
    user:
      name: ${spirng_security_name}
      password: ${spirng_security_password}
  zipkin:
    enabled: true
    base-url: ${zipkin_base_url}
    service:
      name: web-server

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: webservice.log