server:
  port: ${config_service_spring_port}
spring:
  security:
    user:
      name: ${spirng_security_name}
      password: ${spirng_security_password}
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  zipkin:
    enabled: true
    base-url: ${zipkin_base_url}
    service:
      name: config-server




logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: configservice.log
