server:
  port: 8888


spring:
  security:
    user:
      name: ${SPRING-SECURITY-NAME}
      password: ${SPRING-SECURITY-PASSWORD}
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  zipkin:
    enabled: true
    base-url: http://34.116.241.185:9411/
    service:
      name: config-server




logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: configservice.log
