server:
  port: ${apigateway_service_spring_port}
spring:
  main:
    web-application-type: reactive
  zipkin:
    enabled: true
    base-url: ${zipkin_base_url}
    service-name: api-gateway-service
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${auth_service_uri}
          predicates:
            - Path=/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: user-service-follow
          uri: ${user_service_uri}
          predicates:
            - Path=/v1/follow/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: user-service-post
          uri: ${user_service_uri}
          predicates:
            - Path=/v1/post/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: user-service-user
          uri: ${user_service_uri}
          predicates:
            - Path=/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: user-service-profile
          uri: ${user_service_uri}
          predicates:
            - Path=/v1/profile/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
        - id: web-service
          uri: ${web_service_uri}
          predicates:
            - Path=/web/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback
            - RewritePath=/web/?(?<segment>.*), /$\{segment}

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: apigatewayservice.log
